global_frame: map
robot_base_frame: base_link
static_map: true
rolling_window: false
track_unknown_space: true
inflation_radius: 1.5
cost_scaling_factor: 3.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  - {name: static,                    type: "costmap_2d::StaticLayer"}
